name: Ratelimit
run-name: ratelimit
on:
  workflow_dispatch:

jobs:
  rl:
    runs-on: ubuntu-latest
    steps:
    - name: rl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /rate_limit




